# Generated by Django 2.0 on 2018-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='num_left',
            field=models.IntegerField(db_column='doctor_num_left', default=100, verbose_name='剩余挂号人数'),
        ),
    ]
