# Generated by Django 2.0 on 2018-05-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0003_auto_20180520_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('care_id', models.CharField(db_column='care_id_num', default='20180525341819', max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号')),
                ('name', models.CharField(db_column='patient_name', max_length=255, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], db_column='patient_sex', default='男', max_length=32, verbose_name='性别')),
                ('id_num', models.CharField(db_column='patient_id_Num', max_length=255, verbose_name='身份证号')),
                ('birth', models.DateTimeField(db_column='patient_birth', max_length=6, verbose_name='生日')),
                ('phone_num', models.CharField(db_column='patient_phone_num', max_length=255, verbose_name='联系方式')),
                ('address', models.CharField(db_column='patient_address', max_length=255, verbose_name='住址')),
                ('nation', models.CharField(choices=[('0', '中国'), ('1', '美国'), ('2', '英国'), ('3', '韩国'), ('4', '朝鲜'), ('5', '日本'), ('６', '印度尼西亚')], db_column='patient_nation', default='中国', max_length=32, verbose_name='国籍')),
                ('marriage', models.CharField(choices=[('0', '否'), ('1', '是')], db_column='patient_marriage', default='否', max_length=6, verbose_name='婚姻状况')),
                ('job', models.CharField(blank=True, db_column='patient_job', max_length=255, verbose_name='工作')),
                ('parent_name', models.CharField(blank=True, db_column='patient_parent_name', max_length=255, verbose_name='监护人')),
                ('parent_real', models.CharField(blank=True, db_column='patient_parent_real', max_length=255, verbose_name='关系')),
                ('parent_phone', models.CharField(blank=True, db_column='patient_parent_phone', max_length=255, verbose_name='监护人联系方式')),
            ],
        ),
    ]
