# Generated by Django 2.0 on 2018-05-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0005_auto_20180525_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(db_column='patient_address', error_messages={4: '住址不能为空'}, max_length=255, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180525548102', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_num',
            field=models.CharField(db_column='patient_id_Num', error_messages={2: '身份证号不能为空'}, max_length=255, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(db_column='patient_name', error_messages={1: '姓名不能为空'}, max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_num',
            field=models.CharField(db_column='patient_phone_num', error_messages={3: '联系方式不能为空'}, max_length=255, verbose_name='联系方式'),
        ),
    ]
