# Generated by Django 2.0 on 2018-05-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0007_auto_20180526_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergy',
            field=models.CharField(blank=True, db_column='patient_allergy', max_length=255, verbose_name='过敏药物'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sick_his',
            field=models.CharField(blank=True, db_column='patient_sickhis', max_length=255, verbose_name='既往病史'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180526949363', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
