# Generated by Django 2.0 on 2018-05-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0010_auto_20180526_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='_level',
            field=models.CharField(choices=[('0', '医生'), ('1', '护士'), ('2', '主班护士'), ('3', '护士长'), ('4', '科副主任'), ('5', '科主任'), ('6', '住院医师'), ('7', '主任医师'), ('8', '主治医师'), ('9', '副主任医师'), ('10', '院长'), ('11', '副院长')], db_column='level', default='医生', max_length=5, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dep',
            field=models.ForeignKey(db_column='dep_id', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='his06.Department', verbose_name='所属科室'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180527483083', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
