# Generated by Django 2.0 on 2018-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0012_auto_20180527_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='职称')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180527990606', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
