# Generated by Django 2.0 on 2018-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0015_auto_20180527_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='money',
            field=models.FloatField(db_column='doc_money', default=5.0, verbose_name='挂号费'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180527876259', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
