# Generated by Django 2.0 on 2018-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0016_auto_20180527_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='_level',
            field=models.CharField(choices=[('0', '医生'), ('1', '主任医师'), ('2', '主班护士'), ('3', '护士长'), ('4', '科副主任'), ('5', '科主任'), ('6', '住院医师'), ('7', '护士'), ('8', '主治医师'), ('9', '副主任医师'), ('10', '院长'), ('11', '副院长')], db_column='doc_level', default='医生', max_length=5, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180527682706', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
