# Generated by Django 2.0 on 2018-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0017_auto_20180527_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSign',
            fields=[
                ('water_id', models.IntegerField(db_column='water_id', primary_key=True, serialize=False)),
                ('care_id', models.CharField(db_column='care_id', max_length=255, verbose_name='诊疗卡号')),
                ('patient_name', models.CharField(db_column='patient_name', max_length=255, verbose_name='病人姓名')),
                ('patient_sex', models.CharField(db_column='patient_sex', max_length=255, verbose_name='病人性别')),
                ('patient_id', models.CharField(db_column='patient_id', max_length=255, verbose_name='身份证号')),
                ('patient_birth', models.DateTimeField(db_column='patient_birth', verbose_name='出生日期')),
                ('patient_phone', models.CharField(db_column='patient_phone', max_length=255, verbose_name='联系方式')),
                ('patient_address', models.CharField(db_column='patient_address', max_length=255, verbose_name='家庭住址')),
                ('super', models.CharField(db_column='super', max_length=255, verbose_name='科室类型')),
                ('dep', models.CharField(db_column='dep', max_length=255, verbose_name='挂号科室')),
                ('doc_level', models.CharField(db_column='doc_level', max_length=255, verbose_name='医生职称')),
                ('doc_name', models.CharField(db_column='doc_name', max_length=255, verbose_name='医生姓名')),
                ('doc_rom', models.CharField(db_column='doc_room', max_length=255, verbose_name='就诊房间')),
                ('doc_sex', models.CharField(db_column='doc_sex', max_length=255, verbose_name='医生性别')),
                ('sign_kind', models.CharField(db_column='sign_kind', max_length=255, verbose_name='挂号号别')),
                ('is_book', models.CharField(db_column='is_book', max_length=5, verbose_name='是否购买病历')),
                ('should_pay', models.FloatField(db_column='should_pay', verbose_name='应缴金额')),
                ('real_pay', models.FloatField(db_column='real_pay', verbose_name='实付金额')),
                ('ret_pay', models.FloatField(db_column='ret_pay', verbose_name='找回金额')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180527802132', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
