# Generated by Django 2.0 on 2018-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0018_auto_20180527_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsign',
            name='patient_birth',
        ),
        migrations.AddField(
            model_name='patientsign',
            name='care_num',
            field=models.IntegerField(db_column='care_num', default=1, verbose_name='诊疗号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180529458365', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
