# Generated by Django 2.0 on 2018-05-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0019_auto_20180529_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterNum',
            fields=[
                ('id', models.IntegerField(db_column='water_num', default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dep',
            field=models.ForeignKey(db_column='dep_id', default='00101', on_delete=django.db.models.deletion.DO_NOTHING, to='his06.Department', verbose_name='所属科室'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180531542635', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
