# Generated by Django 2.0 on 2018-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0023_auto_20180601_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180601736596', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
        migrations.AlterField(
            model_name='waternum',
            name='id',
            field=models.IntegerField(db_column='water_num', max_length=255, primary_key=True, serialize=False),
        ),
    ]
