# Generated by Django 2.0 on 2018-05-31 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0024_auto_20180601_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsign',
            name='sign_time',
            field=models.DateTimeField(db_column='sign_time', default=datetime.datetime.now, verbose_name='挂号日期'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180601415829', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
