# Generated by Django 2.0 on 2018-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0028_auto_20180601_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='_level',
            field=models.CharField(choices=[('0', '医生'), ('1', '主任医师'), ('2', '主班护士'), ('3', '护士长'), ('4', '科副主任'), ('5', '科主任'), ('6', '住院医师'), ('7', '护士'), ('8', '主治医师'), ('9', '副主任医师'), ('10', '院长'), ('11', '副院长')], db_column='doc_level', default='10', max_length=5, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nation',
            field=models.CharField(choices=[('0', '中国'), ('1', '美国'), ('2', '英国'), ('3', '韩国'), ('4', '朝鲜'), ('5', '日本'), ('６', '印度尼西亚')], db_column='doctor_nation', default='0', max_length=32, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], db_column='doctor_sex', default='male', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180603172842', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
