# Generated by Django 2.0 on 2018-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0029_auto_20180603_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.IntegerField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='date', verbose_name='值班日期')),
                ('time', models.CharField(choices=[('0', '早上'), ('1', '中午'), ('2', '晚上'), ('3', '全天')], max_length=255, verbose_name='值班时间')),
                ('doc_id', models.CharField(max_length=255, verbose_name='医生工号')),
                ('dep', models.CharField(max_length=255, verbose_name='所属科室')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180603875267', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
