# Generated by Django 2.0 on 2018-06-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0031_auto_20180603_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsign',
            old_name='patient_sex',
            new_name='patientSex',
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180603483705', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
