# Generated by Django 2.0 on 2018-06-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0032_auto_20180603_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180603830299', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
        migrations.AlterField(
            model_name='patientsign',
            name='patientSex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], db_column='patient_sex', max_length=255, verbose_name='病人性别'),
        ),
    ]
