# Generated by Django 2.0 on 2018-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0033_auto_20180603_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('me_id', models.CharField(choices=[('0', '消化系统药物'), ('1', '镇热镇痛类药品')], max_length=255, primary_key=True, serialize=False)),
                ('me_name', models.CharField(max_length=255, verbose_name='药品大类')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180603982357', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
