# Generated by Django 2.0 on 2018-06-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0035_auto_20180603_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(db_column='medicineName', max_length=255, verbose_name='药品名称')),
                ('medicineId', models.CharField(db_column='medicineId', max_length=255, verbose_name='药品ID')),
                ('max_num', models.IntegerField(db_column='max_num', verbose_name='药品使用最大量')),
                ('all_num', models.IntegerField(db_column='all_num', verbose_name='药品总量')),
                ('left_num', models.IntegerField(db_column='left_num', verbose_name='药品剩余量')),
                ('sm_id', models.ForeignKey(db_column='sm_id', on_delete=django.db.models.deletion.DO_NOTHING, to='his06.MedicineKind')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180603499414', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
