# Generated by Django 2.0 on 2018-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0036_auto_20180603_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinetype',
            name='me_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180603196198', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
