# Generated by Django 2.0 on 2018-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0037_auto_20180603_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(db_column='price', default=100, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180604345081', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
