# Generated by Django 2.0 on 2018-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0038_auto_20180604_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(db_column='pro_id', max_length=255, verbose_name='项目ID')),
                ('pro_name', models.CharField(db_column='pro_name', max_length=255, verbose_name='项目名称')),
                ('price', models.IntegerField(db_column='price', verbose_name='价格')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180604234493', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
