# Generated by Django 2.0 on 2018-06-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0041_auto_20180609_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180609363804', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
        migrations.AlterField(
            model_name='patientsign',
            name='doc_level',
            field=models.ForeignKey(db_column='doc_level', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='his06.Title', verbose_name='医生职称'),
        ),
    ]
