# Generated by Django 2.0 on 2018-06-09 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0044_auto_20180609_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_date',
            field=models.DateTimeField(db_column='work_date', default=django.utils.timezone.now, verbose_name='值班日期'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180609747501', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
