# Generated by Django 2.0 on 2018-06-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0045_auto_20180609_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='work_date',
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180609443683', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
