# Generated by Django 2.0 on 2018-06-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0047_auto_20180610_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktime',
            old_name='date',
            new_name='work_date',
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180610228414', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
    ]
