# Generated by Django 2.0 on 2018-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his06', '0048_auto_20180610_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='care_id',
            field=models.CharField(db_column='care_id_num', default='20180610353158', error_messages={0: '该诊疗卡号不存在'}, max_length=255, primary_key=True, serialize=False, verbose_name='诊疗卡号'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='work_date',
            field=models.DateField(db_column='date', verbose_name='值班日期'),
        ),
    ]
